### PR TITLE
fix: support TypedDict schema generation

### LINKED ISSUE #2973: Schema generation does not handle TypedDict as dict
I have code which used existing TypedDict classes as predict input parameters. Neither static nor legacy schema generation treats TypedDict as a dict.

For legacy schema generation, I can include the following in my module which lets the schema generation handle TypedDict as dict.

```python
class TypedDictCoder(Coder):
    """This class lets cog accept TypedDict as a dict Input."""

    @staticmethod
    def factory(tpe: type) -> Optional["TypedDictCoder"]:
        if issubclass(tpe, dict):
            return TypedDictCoder()
        return None

    def encode(self, x: dict) -> dict:
        return x

    def decode(self, x: dict) -> dict:
        return x
```

This work around will not help with static schema generation. Both legacy and static schema generation should handle TypedDict as dict.

There are several instances of code like `tpe is dict` which probably should be something like `issubclass(tpe, dict)`. Similar equality with `dict` checks are in the Go static schema generation code.

### PR DESCRIPTION
**Pull request by markphelps**
Fixes: #2973 

## Summary
- fix legacy runtime schema generation so `TypedDict` inputs are treated like dicts without accepting arbitrary dict subclasses
- add static schema support for `TypedDict` inputs and outputs, including qualified imports, inheritance, and `Required` / `NotRequired` key semantics
- add regression coverage in Python, Go parser tests, and integration txtar scripts for static and legacy TypedDict paths

## Notes
- added integration txtar coverage for `typeddict_input`, `typeddict_input_legacy`, and `typeddict_output`

### CODE REVIEW

File: pkg/schema/python/parser.go [hunk 1]
```diff
@@ -71,7 +72,7 @@ func ParsePredictor(source []byte, predictRef string, mode schema.Mode, sourceDi
 	isMethod := firstParamIsSelf(paramsNode, source)
 
 	// 7. Extract parameters
-	inputs, err := extractInputs(paramsNode, source, methodName, isMethod, imports, inputRegistry, moduleScope)
+	inputs, err := extractInputs(paramsNode, source, methodName, isMethod, imports, inputRegistry, moduleScope, typedDicts)
```
Comment (markphelps) [inline pkg/schema/python/parser.go]: this is a lot of params. we should make this take in a struct

File: pkg/schema/python/parser.go [hunk 2]
```diff
@@ -43,10 +43,11 @@ func ParsePredictor(source []byte, predictRef string, mode schema.Mode, sourceDi
...
 	moduleScope := collectModuleScope(root, source)
 
-	// 3. Collect BaseModel subclasses (local file first, then cross-file)
-	modelClasses := collectModelClasses(root, source, imports)
+	// 3. Collect schema object classes (BaseModel and TypedDict) locally first,
+	// then across local imports.
+	modelClasses, typedDicts := collectModelClasses(root, source, imports)
 	if sourceDir != "" {
-		resolveExternalModels(sourceDir, imports, modelClasses)
+		resolveExternalModels(sourceDir, imports, modelClasses, typedDicts)
```
Comment (markphelps) [inline pkg/schema/python/parser.go]: wondering if this is getting into struct as param territory too

**Review by michaeldwan — APPROVED** [review]
nice fix
